version: '3.8'

services:
  backend:
    container_name: django_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis


  frontend:
    container_name: vue_frontend
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  redis:
        image: "redis:alpine"
        container_name: redis_container